# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision :shell, path: "trebureus/inserciontotal.sh"
  config.vm.network "forwarded_port", guest: 80, host: 7777
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "trebureusprueba2"
    vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
  end  
end